theme: jekyll-theme-midnight

# Site settings
title: Nine-Light                     #你博客的标题
SEOTitle: 你的博客 | You Blog        #显示在浏览器上搜索的时候显示的标题
email: cwm1045577196@gmail.com    
description: "代码新手"              #网站介绍
# header-img: img/post-bg-rwd.jpg     #显示在首页的背景图片
keyword: "Nine-Light, blog, Nine-Light blog, javascript, c++, unreal" #关键词
url: "https://nine-light.github.io"          # 这个就是填写你的博客地址


# Sidebar settings
sidebar: true                           # 是否开启侧边栏.
sidebar-about-description: "请多指教"
# sidebar-avatar:/img/avatar-by.JPG      # 你的个人头像 这里你可以改成我在img文件夹中的两张备用照片 img/avatar-m 或 avatar-g


# SNS settings
RSS: false
bilibili_username: 隙游尘
zhihu_username: 隙游尘
github_username: Nine-Light
